// Cross-check with PowerDesigner itself: the owner's class models (.cdm) are generated by our
// CDM → PDM rules and compared with the physical models PowerDesigner 16 generated from them (.pdm):
// tables, column order, nullability, primary keys, foreign keys and alternate keys.

import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { generatePdm } from '../src/core/cdm2pdm'
import { importPowerDesigner } from '../src/core/import/powerdesigner'
import { readPdTables, type PdTable } from '../src/core/import/pdm-reader'
import type { Pdm } from '../src/core/pdm'

const fixture = (f: string) => readFileSync(new URL(`./fixtures/${f}`, import.meta.url), 'utf-8')

/** Key columns and attributes keep their order; the FK-only columns between them are compared as a set (PD orders them by creation). */
function line(cols: { name: string; pk: boolean; nullable: boolean }[], fkCols: string[], fks: string[], aks: string[]): string {
  const fk = new Set(fkCols.map((c) => c.toLowerCase()))
  const fmt = (c: (typeof cols)[number]) => `${c.name.toLowerCase()}${c.pk ? '*' : ''}${c.nullable ? '?' : ''}`
  const pk = cols.filter((c) => c.pk).map(fmt)
  const mid = cols.filter((c) => !c.pk && fk.has(c.name.toLowerCase())).map(fmt).sort()
  const rest = cols.filter((c) => !c.pk && !fk.has(c.name.toLowerCase())).map(fmt)
  return `${[...pk, ...mid, ...rest].join(', ')} | FK ${fks.sort().join('; ')} | AK ${aks.sort().join('; ')}`
}

function fromPd(tables: PdTable[]): Map<string, string> {
  return new Map(
    tables.map((t) => [
      t.code,
      line(
        t.columns.map((c) => ({ name: c.code, pk: t.primaryKey.includes(c.code), nullable: !c.mandatory })),
        t.foreignKeys.flatMap((f) => f.columns),
        t.foreignKeys.map((f) => `${f.parent}(${f.columns.join(',').toLowerCase()})`),
        t.alternateKeys.map((k) => k.join(',').toLowerCase()),
      ),
    ]),
  )
}

function fromOurs(pdm: Pdm, rename: (s: string) => string): Map<string, string> {
  return new Map(
    pdm.tables.map((t) => [
      rename(t.name.toUpperCase()),
      line(
        t.columns.map((c) => ({ name: c.name, pk: !!t.primaryKey?.columns.includes(c.name), nullable: c.nullable })),
        t.foreignKeys.flatMap((f) => f.columns),
        t.foreignKeys.map((f) => `${rename(f.refTable.toUpperCase())}(${f.columns.join(',').toLowerCase()})`),
        t.alternateKeys.map((k) => k.columns.join(',').toLowerCase()),
      ),
    ]),
  )
}

describe.each([
  // The CDM was edited after its PDM was generated: one attribute added (`ID?` → id_).
  { name: 'TV Show', file: 'tv-show', rename: (t: string) => t, drop: ', id_?' },
  // The CDM entity Year was renamed Academic_Year after its PDM was generated.
  { name: 'University', file: 'university', rename: (t: string) => (t === 'ACADEMIC_YEAR' ? 'YEAR' : t), drop: '' },
])('$name', ({ name, file, rename, drop }) => {
  it('our PDM equals the one PowerDesigner generated', () => {
    const pd = fromPd(readPdTables(fixture(`${file}.pdm`)))
    const ours = fromOurs(generatePdm(importPowerDesigner(fixture(`${file}.cdm`), `${name}.cdm`).model), rename)
    if (drop) for (const [k, v] of ours) ours.set(k, v.replace(drop, ''))
    expect(ours).toEqual(pd)
  })
})
