import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1800, height: 1000 } })
await p.goto('http://localhost:5173/')
await p.getByText('Start with an empty model').click()
await p.getByRole('button', { name: /Examples/ }).click()
await p.getByRole('menuitem', { name: 'Other cases…' }).click()
await p.getByRole('button', { name: /Build it yourself/ }).nth(1).click()
await p.waitForTimeout(1000)
const info = () => p.evaluate(() => ({ t: document.querySelector('.react-flow__viewport').style.transform, pane: document.querySelector('.react-flow').getBoundingClientRect().toJSON(), hint: [...document.querySelectorAll('div')].find(d => d.firstElementChild?.textContent.trim() === 'Start a conceptual model')?.getBoundingClientRect().toJSON() }))
console.log(JSON.stringify(await info()))
await p.mouse.dblclick(470, 420); await p.waitForTimeout(600)
const m = JSON.parse(await p.evaluate(() => localStorage.getItem('stratasql.trainer.model')))
console.log(JSON.stringify(m.entities[0].position), JSON.stringify(await info()))
console.log(JSON.stringify(await p.locator('.react-flow__node').first().boundingBox()))
await b.close()
