// PostgreSQL DDL from a PDM — the dialect of the in-browser SQL sandbox (PGlite).
// Keys, FKs, CHECKs and NOT NULL behave as in SQL Server, so a row rejected here is rejected there.
// Identifiers stay unquoted (Postgres folds them to lower case), so `SELECT * FROM episode` and
// `SELECT * FROM EPISODE` both work in the console.

import type { Pdm, PdmColumn, PdmTable } from '../pdm'

/** Postgres truncates identifiers to 63 bytes; constraint names in errors come back truncated. */
export const PG_MAX_IDENT = 63

/** Conceptual type → PostgreSQL type. */
export function postgresType(c: Pick<PdmColumn, 'dataType' | 'length' | 'precision'>): string {
  switch (c.dataType) {
    case 'Integer':
      return 'integer'
    case 'Short integer':
      return 'smallint'
    case 'Long integer':
      return 'bigint'
    case 'Decimal':
      return c.length !== undefined ? `numeric(${c.length}${c.precision !== undefined ? `,${c.precision}` : ''})` : 'numeric(18,2)'
    case 'Float':
      return 'double precision'
    case 'Money':
      return 'numeric(19,4)'
    case 'Boolean':
      return 'boolean'
    case 'Characters':
      return `char(${c.length ?? 1})`
    case 'Variable characters':
      return c.length !== undefined ? `varchar(${c.length})` : 'text'
    case 'Text':
      return 'text'
    case 'Date':
      return 'date'
    case 'Time':
      return 'time'
    case 'Date & time':
      return 'timestamp'
    case 'Binary':
      return 'bytea'
  }
}

// PostgreSQL reserved key words (docs, appendix C: "reserved" and "reserved, can be function or type").
const RESERVED = new Set(
  `ALL ANALYSE ANALYZE AND ANY ARRAY AS ASC ASYMMETRIC AUTHORIZATION BINARY BOTH CASE CAST CHECK COLLATE COLLATION
  COLUMN CONCURRENTLY CONSTRAINT CREATE CROSS CURRENT_CATALOG CURRENT_DATE CURRENT_ROLE CURRENT_SCHEMA CURRENT_TIME
  CURRENT_TIMESTAMP CURRENT_USER DEFAULT DEFERRABLE DESC DISTINCT DO ELSE END EXCEPT FALSE FETCH FOR FOREIGN FREEZE
  FROM FULL GRANT GROUP HAVING ILIKE IN INITIALLY INNER INTERSECT INTO IS ISNULL JOIN LATERAL LEADING LEFT LIKE LIMIT
  LOCALTIME LOCALTIMESTAMP NATURAL NOT NOTNULL NULL OFFSET ON ONLY OR ORDER OUTER OVERLAPS PLACING PRIMARY REFERENCES
  RETURNING RIGHT SELECT SESSION_USER SIMILAR SOME SYMMETRIC SYSTEM_USER TABLE TABLESAMPLE THEN TO TRAILING TRUE
  UNION UNIQUE USER USING VARIADIC VERBOSE WHEN WHERE WINDOW WITH`.split(/\s+/),
)

/** Unquoted when plain and not reserved; otherwise double-quoted in lower case (what folding would give). */
export function pgIdent(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !RESERVED.has(name.toUpperCase())) return name
  return `"${name.toLowerCase().replace(/"/g, '""')}"`
}

const list = (cols: string[]) => cols.map(pgIdent).join(', ')

function createTable(t: PdmTable): string {
  const width = Math.max(20, ...t.columns.map((c) => pgIdent(c.name).length + 1))
  const typeWidth = Math.max(16, ...t.columns.map((c) => postgresType(c).length + 1))
  const lines = t.columns.map((c) => `   ${pgIdent(c.name).padEnd(width)} ${postgresType(c).padEnd(typeWidth)} ${c.nullable ? 'NULL' : 'NOT NULL'}`)
  if (t.primaryKey) lines.push(`   CONSTRAINT ${pgIdent(t.primaryKey.name)} PRIMARY KEY (${list(t.primaryKey.columns)})`)
  for (const ak of t.alternateKeys) lines.push(`   CONSTRAINT ${pgIdent(ak.name)} UNIQUE (${list(ak.columns)})`)
  for (const ck of t.checks) lines.push(`   CONSTRAINT ${pgIdent(ck.name)} CHECK (${ck.expression})`)
  return `-- Table ${t.name}\nCREATE TABLE ${pgIdent(t.name)} (\n${lines.join(',\n')}\n);`
}

export function generatePostgres(pdm: Pdm): string {
  const out: string[] = [`-- PostgreSQL DDL for "${pdm.name}" — generated by StrataSQL (sandbox dialect).`]
  out.push(...pdm.tables.map(createTable))
  for (const t of pdm.tables)
    for (const fk of t.foreignKeys)
      out.push(
        `ALTER TABLE ${pgIdent(t.name)}\n   ADD CONSTRAINT ${pgIdent(fk.name)} FOREIGN KEY (${list(fk.columns)})\n` +
          `      REFERENCES ${pgIdent(fk.refTable)} (${list(fk.refColumns)});`,
      )
  return out.join('\n\n') + '\n'
}
