// SQL Server DDL from a PDM: CREATE TABLE with PK / UNIQUE / CHECK, then FKs as ALTER TABLE
// (so table order never matters, cycles included) — the same layout PowerDesigner generates.

import type { PdmColumn, PdmTable, Pdm } from '../pdm'

export interface SqlServerOptions {
  /** Prepend DROP statements so the script can be re-run on the same database. */
  drop?: boolean
}

/** Conceptual type → SQL Server type (PowerDesigner's mapping for SQL Server). */
export function sqlServerType(c: Pick<PdmColumn, 'dataType' | 'length' | 'precision'>): string {
  switch (c.dataType) {
    case 'Integer':
      return 'int'
    case 'Short integer':
      return 'smallint'
    case 'Long integer':
      return 'bigint'
    case 'Decimal':
      return c.length !== undefined ? `decimal(${c.length}${c.precision !== undefined ? `,${c.precision}` : ''})` : 'decimal(18,2)'
    case 'Float':
      return 'float'
    case 'Money':
      return 'money'
    case 'Boolean':
      return 'bit'
    case 'Characters':
      return `char(${c.length ?? 1})`
    case 'Variable characters':
      return c.length !== undefined ? `varchar(${c.length})` : 'varchar(max)'
    case 'Text':
      return 'varchar(max)'
    case 'Date':
      return 'date'
    case 'Time':
      return 'time'
    case 'Date & time':
      return 'datetime'
    case 'Binary':
      return c.length !== undefined ? `varbinary(${c.length})` : 'varbinary(max)'
  }
}

// T-SQL reserved keywords (Microsoft docs). Identifiers equal to one of them are bracketed.
const RESERVED = new Set(
  `ADD ALL ALTER AND ANY AS ASC AUTHORIZATION BACKUP BEGIN BETWEEN BREAK BROWSE BULK BY CASCADE CASE CHECK
  CHECKPOINT CLOSE CLUSTERED COALESCE COLLATE COLUMN COMMIT COMPUTE CONSTRAINT CONTAINS CONTAINSTABLE CONTINUE
  CONVERT CREATE CROSS CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DBCC
  DEALLOCATE DECLARE DEFAULT DELETE DENY DESC DISK DISTINCT DISTRIBUTED DOUBLE DROP DUMP ELSE END ERRLVL ESCAPE
  EXCEPT EXEC EXECUTE EXISTS EXIT EXTERNAL FETCH FILE FILLFACTOR FOR FOREIGN FREETEXT FREETEXTTABLE FROM FULL
  FUNCTION GOTO GRANT GROUP HAVING HOLDLOCK IDENTITY IDENTITY_INSERT IDENTITYCOL IF IN INDEX INNER INSERT
  INTERSECT INTO IS JOIN KEY KILL LEFT LIKE LINENO LOAD MERGE NATIONAL NOCHECK NONCLUSTERED NOT NULL NULLIF OF
  OFF OFFSETS ON OPEN OPENDATASOURCE OPENQUERY OPENROWSET OPENXML OPTION OR ORDER OUTER OVER PERCENT PIVOT PLAN
  PRECISION PRIMARY PRINT PROC PROCEDURE PUBLIC RAISERROR READ READTEXT RECONFIGURE REFERENCES REPLICATION
  RESTORE RESTRICT RETURN REVERT REVOKE RIGHT ROLLBACK ROWCOUNT ROWGUIDCOL RULE SAVE SCHEMA SECURITYAUDIT SELECT
  SEMANTICKEYPHRASETABLE SEMANTICSIMILARITYDETAILSTABLE SEMANTICSIMILARITYTABLE SESSION_USER SET SETUSER
  SHUTDOWN SOME STATISTICS SYSTEM_USER TABLE TABLESAMPLE TEXTSIZE THEN TO TOP TRAN TRANSACTION TRIGGER TRUNCATE
  TRY_CONVERT TSEQUAL UNION UNIQUE UNPIVOT UPDATE UPDATETEXT USE USER VALUES VARYING VIEW WAITFOR WHEN WHERE
  WHILE WITH WITHIN WRITETEXT`.split(/\s+/),
)

/** Brackets identifiers that are reserved words or not plain `[A-Za-z_][A-Za-z0-9_]*`. */
export function quoteIdent(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !RESERVED.has(name.toUpperCase())) return name
  return `[${name.replace(/]/g, ']]')}]`
}

const list = (cols: string[]) => cols.map(quoteIdent).join(', ')

function comment(text: string): string {
  return text
    .split('\n')
    .map((l) => `-- ${l}`.trimEnd())
    .join('\n')
}

function createTable(t: PdmTable): string {
  const width = Math.max(20, ...t.columns.map((c) => quoteIdent(c.name).length + 1))
  const typeWidth = Math.max(16, ...t.columns.map((c) => sqlServerType(c).length + 1))
  const lines = t.columns.map(
    (c) => `   ${quoteIdent(c.name).padEnd(width)} ${sqlServerType(c).padEnd(typeWidth)} ${c.nullable ? 'NULL' : 'NOT NULL'}`,
  )
  if (t.primaryKey) lines.push(`   CONSTRAINT ${quoteIdent(t.primaryKey.name)} PRIMARY KEY (${list(t.primaryKey.columns)})`)
  for (const ak of t.alternateKeys) lines.push(`   CONSTRAINT ${quoteIdent(ak.name)} UNIQUE (${list(ak.columns)})`)
  for (const ck of t.checks) lines.push(`   CONSTRAINT ${quoteIdent(ck.name)} CHECK (${ck.expression})`)
  const head = [`-- Table ${t.name}`]
  if (t.comment) head.push(comment(t.comment))
  return `${head.join('\n')}\nCREATE TABLE ${quoteIdent(t.name)} (\n${lines.join(',\n')}\n)\nGO`
}

export function generateSqlServer(pdm: Pdm, opts: SqlServerOptions = {}): string {
  const out: string[] = [comment(`SQL Server DDL for "${pdm.name}" — generated by StrataSQL from the conceptual model.`)]
  const fks = pdm.tables.flatMap((t) => t.foreignKeys.map((fk) => ({ t, fk })))

  if (opts.drop) {
    const drops = fks.map(
      ({ t, fk }) =>
        `IF OBJECT_ID('${fk.name.replace(/'/g, "''")}', 'F') IS NOT NULL\n   ALTER TABLE ${quoteIdent(t.name)} DROP CONSTRAINT ${quoteIdent(fk.name)}\nGO`,
    )
    drops.push(...pdm.tables.map((t) => `DROP TABLE IF EXISTS ${quoteIdent(t.name)}\nGO`))
    out.push(`${comment('Drop the previous version (FKs first, so tables can go in any order)')}\n${drops.join('\n\n')}`)
  }

  out.push(...pdm.tables.map(createTable))

  for (const { t, fk } of fks)
    out.push(
      `ALTER TABLE ${quoteIdent(t.name)}\n   ADD CONSTRAINT ${quoteIdent(fk.name)} FOREIGN KEY (${list(fk.columns)})\n` +
        `      REFERENCES ${quoteIdent(fk.refTable)} (${list(fk.refColumns)})\nGO`,
    )
  return out.join('\n\n') + '\n'
}
